### ISSUE TITLE
tf测试更新不了

### ISSUE THREAD

**Issue by wl851229** [ClashForIOS/ClashPro#8]
之前申请成功了如今更新不了，是清掉了还是异常了
要么上架，要么全清了，用没几天就失效，烦死了

**Comment by ClashForIOS** [comment]
iOS, MacOS: (ClashProTF) TestFlight https://testflight.apple.com/join/TIygdVem
iOS, MacOS: (ClashPro) AppStore https://apps.apple.com/us/app/clashpro/id6450642232
